job('First-Maven-Project-Via-DSL') {
    // tools {
    //     maven 'LocalMaven' // Specify the name of the Maven installation configured in Jenkins
    // }
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git(" https://github.com/deep-bansal/learning_jenkins.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
            goals('clean package') // Specify Maven goals
            mavenInstallation('LocalMaven') // Specify the Maven installation name
            pom('path/to/your/pom.xml') // Specify the path to your pom.xml file
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
