job('First-Maven-Project-Via-DSL') {
    // tools {
    //     maven 'LocalMaven' // Specify the name of the Maven installation configured in Jenkins
    // }
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git(" https://github.com/deep-bansal/learning_jenkins.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
         mavenInstallation('LocalMaven') // Specify the correct Maven version
        goals('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
